version: '3.8'

services:

    mysql:
        image: mysql:latest
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: 'test'
            MYSQL_ROOT_PASSWORD: 'secret'
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - '3306:3306'
        expose:
            - '3306'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            PMA_USER: 'root'
            PMA_PASSWORD: 'secret'
            PMA_HOST: mysql
        ports:
            - '23306:80'
        
    postgresql:
        image: postgres:14.1-alpine
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
        ports:
            - '5432:5432'
        volumes:
            - postgre_data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=1234
        ports:
            - '25432:80'
        volumes:
            - pgadmin_data:/var/lib/pgadmin
    

    mongo:
        image: mongo:latest
        container_name: mongodb
        environment:
            DB_NAME: documents
            #MONGO_INITDB_ROOT_USERNAME: root
            #MONGO_INITDB_ROOT_PASSWORD: 12345678
            #DB_USER: $DB_USER
            #DB_PASSWORD: $DB_PASSWORD
        volumes:
            - mongo_data:/data/db
        ports:
            - '27017:27017'
        expose:
            - '27017'
        profiles:
            - donotstart

    zookeeper:
        image: confluentinc/cp-zookeeper:7.0.1
        hostname: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SYNC_LIMIT: 2
        profiles:
            - donotstart

    kafka:
        image: confluentinc/cp-kafka:7.0.1
        hostname: kafka
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        profiles:
            - donotstart

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        restart: "no"
        ports:
            - "28080:8080"
        environment:
            KAFKA_CLUSTER_0_NAME: local
            KAFKA_CLUSTER_0_BOOTSTRAPSERVERS: kafka:29092
        depends_on:
            - kafka
        profiles:
            - donotstart

volumes:
    mysql_data:
    mongo_data:
    postgre_data:
    pgadmin_data:


networks:
    default: 
        name: local-net
